#!/bin/bash

echo "🗺️  PILOTES MAP SETUP GUIDE"
echo "=========================="
echo ""
echo "Para usar tu mapa detallado de Pilotes, necesitas:"
echo ""
echo "1. 📁 Guardar tu imagen como:"
echo "   /public/assets/maps/pilotes_map.jpg"
echo ""
echo "2. 📐 Recomendaciones de formato:"
echo "   - Resolución: 1024x1024 píxeles (cuadrada)"
echo "   - Formato: JPG o PNG"
echo "   - Tamaño: < 2MB para mejor rendimiento"
echo ""
echo "3. 🎨 Si quieres crear un mapa de altura personalizado:"
echo "   - Guarda una versión en escala de grises como:"
echo "   - /public/assets/maps/pilotes_height.jpg"
echo "   - Blanco = Elevaciones máximas (castillo, torres)"
echo "   - Gris = Elevaciones medias (edificios, murallas)" 
echo "   - Negro = Elevaciones mínimas (agua, terreno bajo)"
echo ""
echo "4. 🔄 El sistema incluye:"
echo "   - ✅ Detección automática de la imagen"
echo "   - ✅ Generación procedural si no encuentra la imagen"
echo "   - ✅ Creación automática de mapa de altura"
echo "   - ✅ Fallback a mapa básico si hay problemas"
echo ""
echo "📂 Estructura de directorios:"
echo "public/"
echo "  assets/"
echo "    maps/"
echo "      pilotes_map.jpg     ← Tu imagen principal"
echo "      pilotes_height.jpg  ← Opcional: mapa de altura"
echo ""
echo "🚀 Una vez que copies la imagen, recarga la página"
echo "   y deberías ver tu mapa con relieve 3D!"